name: Render vignette Gen3Authentication.Rmd as README.md

on:
  workflow_dispatch:
  push:
    paths:
    - vignettes/Gen3Authentication.Rmd

jobs:
  render:
    name: Render README
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2'
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown, remotes, and the local package
        run: |
          install.packages(c("remotes", "BiocManager"))
          BiocManager::install(version = "devel", ask = FALSE)
          BiocManager::install(c("Bioconductor/AnVIL", "rmarkdown"))
          remotes::install_local(".")
        shell: Rscript {0}
      - name: Render vignette
        run: Rscript -e 'rmarkdown::render("vignettes/Gen3Authentication.Rmd", output_file = "../README.md", md_document())'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit README.md -m 'Re-build vignettes/Gen3Authentication.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"